### ISSUE TITLE
Doors Buying issue

### ISSUE THREAD

**Issue by deadspidervenom** [astepantsov/gmod-advanced-door-system#2]
So i set the doors group to bank (Banker and bank guard (also tried them separately from the group), however it does not let me buy them as the banker or bank guard job.

If this was not a intended feature, then my mistake was just trying to make it so the bank could rent doors to people to access the bank.

**Comment by deadspidervenom** [comment]
oops i think you can ignore this, used it wrong.

**Comment by astepantsov** [comment]
Closed due to being resolved
